
var imoveis = [
    {
        "id": 1,
        "titulo": "Casa a venda no São Bento",
        "tipo": "Casa",
        "categoria": "Vender",
        "bairro": "Sion",
        "endereço": "Rua do Ouro, 682 - Belo Horizonte",
        "area": 106,
        "quartos": 5,
        "banheiro": 1,
        "vaga": 1,
        "valor": "1.415.000",
        "descricao": "Com armários nos quartos, com elevador. A aproximadamente 290 metros de O Boiadeiro Pizzaria, com farmácia, padaria e supermercado próximo.",
        "image": "../img/imoveis/casa1.jpg"
    },
    {
        "id": 2,
        "titulo": "Cobertura à venda no Bandeirantes",
        "tipo": "Cobertura",
        "categoria": "Vender",
        "bairro": "Bandeirantes",
        "endereço": "Rua Andrade, 572 - Belo Horizonte",
        "area": 62,
        "quartos": 2,
        "banheiro": 2,
        "vaga": 1,
        "valor": "580.00",
        "descricao": "Cobertura: varanda 2 salas, cozinha americana, área de serviço independente, escritório, 4 vagas de garagem.Detalhes da cobertura: Tipo de cobertura Duplex, com 101m² de área construida.",
        "image": "../img/imoveis/apartamento3.jpg"
    },
    {
        "id": 3,
        "titulo": "Loja para alugar em Nova lima",
        "tipo": "Loja",
        "categoria": "Alugar",
        "bairro": "Liberdade",
        "endereço": "Rua Orquidia, 222 - Belo Horizonte",
        "area": 45,
        "quartos": 0,
        "banheiro": 4,
        "vaga": 3,
        "valor": "2.200",
        "descricao": "Que aceita permuta, com elevador, com varanda, com armários nos quartos. A aproximadamente 230 metros de Allia Gran Hotel.",
        "image": "../img/imoveis/loja1.jpg"
    },
    {
        "id": 4,
        "titulo": "Apartamento para vender no Centro",
        "tipo": "Apartamento",
        "categoria": "Alugar",
        "bairro": "Centro",
        "area": 76,
        "quartos": 2,
        "banheiro": 4,
        "vaga": 3,
        "valor": "1.500",
        "descricao": "Apartamento com 76m² para alugar no bairro do Centro, com 02 quartos, 02 vagas de garagem, perto do EPA Supermercados, da Escola Municipal Aurélio Pires e dos Correios, elevador e serviços.",
        "image": "../img/imoveis/apartamento1.jpg"
    },
    {
        "id": 5,
        "titulo": "Casa para alugar no Luxemburgo",
        "tipo": "Casa",
        "categoria": "Alugar",
        "bairro": "Centro",
        "area": 70,
        "quartos": 4,
        "banheiro": 4,
        "vaga": 3,
        "valor": "2.800",
        "descricao": "Que aceita permuta, com elevador, com varanda, com armários nos quartos. A aproximadamente 230 metros de Allia Gran Hotel.",
        "image": "../img/imoveis/casa2.jpg"
    },
    {
        "id": 6,
        "titulo": "Apartamento para vender no Mangabeiras",
        "tipo": "Apartamento",
        "categoria": "Alugar",
        "bairro": "Centro",
        "area": 98,
        "quartos": 3,
        "banheiro": 4,
        "vaga": 3,
        "valor": "1.500",
        "descricao": "Que aceita permuta, com elevador, com varanda, com armários nos quartos. A aproximadamente 230 metros de Allia Gran Hotel.",
        "image": "../img/imoveis/apartamento2.jpg"
    }
]

